apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedera-connector
  labels:
    component: hedera-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hedera-connector
  template:
    metadata:
      labels:
        component: hedera-connector
    spec:
      volumes:
        {{- if eq .Values.wallet.type "filesystem" }}
        - name: wallet
          persistentVolumeClaim:
            claimName: wallet
        {{- end }}
        - name: credentials
          secret:
            secretName: credentials
      containers:
        - name: hedera-connector
          image: localhost:5000/hedera-connector:1.0.0
          imagePullPolicy: Always
          env:
            - name: NODE_HEDERA_ACCOUNT_ID
              value: {{ .Values.hedera.account.id }}
            - name: WALLET_TYPE
              value: {{ .Values.wallet.type }}
            - name: HEDERA_NETWORK
              value: testnet
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: credentials
              mountPath: /opt/credentials
              readOnly: false
            {{- if eq .Values.wallet.type "filesystem" }}
            - name: wallet
              mountPath: /opt/wallet
            {{- end }}