{{- if eq (.Values.global.wallet.type) "filesystem" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallet
  labels:
    component: hedera-connector
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
{{- end }}