apiVersion: v1
kind: Service
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
  name: hedera-connector-database
spec:
  selector:
    select: hedera-connector-database
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
  type: ClusterIP
