{{- if (eq .Values.global.wallet.type "couchdb") }}
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  {{- if (eq .Values.global.settings.local true) }}
  username: user
  password: pass
  {{- else }}
  username: {{ .Values.global.wallet.couchdb.username }}
  password: {{ .Values.global.wallet.couchdb.password }}
  {{- end }}
{{- end }}