{{- if and (eq .Values.global.wallet.type "couchdb") (eq .Values.global.settings.local true) }}
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  username: user
  password: pass
{{- end }}